- name: 'copy {{ multicopyname }} files to the remote host'
  copy:
    src: '{{ workdir }}/{{ fqdn }}/{{ item }}'
    dest: '{{ item }}'
    backup: '{{ backup }}'
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: '{{ mode }}'
  with_items: "{{ src_files }}"

