- name: make sure the db password is not stored in the repository
  lineinfile:
    dest: '{{ account_dest }}'
    regexp: "^{{ account_pass_key }}=.*"
    line: "{{ account_pass_key }}={{ account_password_placeholder }}"
  connection: local
