default__postgresql__user: 'postgres'
default__postgresql__group: 'postgres'
default__postgresql__edit_db: true

default__liferay__db_name: 'liferay'
default__liferay__db_user: 'liferay'

default__liferay_db_credentials_key: 'jdbc.default.password'
default__liferay_db_credentails_name: 'liferay_db'

