#*  This playbook creates a vm on a KVM host (via virt-install for now).
#* Currently only debian jessie on amd64 via preseed is supported, extending
#* should not be too difficult, but we had to start somewhere..
#*  The playbook is intended to be used by 'maestro', which gets the necessary
#* host and vm info from the knowledge base (reclass-inventory).
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  The following arguments are mandatory:
#*   - 'new__hostname'
#*   - 'host' (dict)

- hosts: host.KVM
  vars:
    new: '{{ host.resource[new__hostname] }}'
    new__system_disk: '{{ new.disk | selectattr("system") | first() }}'
    # TODO why does attr() not work as expected?
    new__system_disk_attr:
      bus: '{{ host.virt.storage[new__system_disk.meta.pool].bus }}'
      cache: '{{ host.virt.storage[new__system_disk.meta.pool].cache }}'
      name: '{{ new__system_disk.name }}'
      pool: '{{ new__system_disk.pool }}'
      target: '{{ host.virt.storage[new__system_disk.meta.pool].path }}/{{ new__hostname }}-{{ new__system_disk.name }}'
    new__system_net: '{{ new.net | selectattr("primary") | first() }}'
  roles:
    - virt-install

