#*  This playbook wrapps the copy module. It passes the custom kivitendo
#* templates for the host as a list to 'src'. Use '-a' to pass
#* further parameters to ansible (as '-e'). See ansible copy for
#* details.
#*  You might want to do a `maestro.sh merge` first.
#*  No arguments are needed.

- hosts: role.erp

  roles:
    - deploy-kivitendo-templates
