#*  This playbook wrapps the copy, file and lineinfile modules.
#* It mainly passes files needed for a runnung tomcat installation
#* as a list to 'src' to the hosts. Use '-a' to pass
#* further parameters to ansible (as '-e'). See ansible copy for
#* details.
#*  You might want to do a `maestro.sh merge` first.
#*  No arguments are needed.

- hosts: app.tomcat
  become: True
  roles:
    - deploy-tomcat-core
    - deploy-tomcat-service
