#*  This playbook wrapps the copy module. It passes the most basic
#* configs for each host from a list to 'dest'. Use '-a' to pass
#* further parameters to ansible (as '-e'). See ansible fetch for
#* details. 
#*  You might want to do a `maestro.sh merge` first.
#*  No arguments are needed.

- hosts: os.debian:os.centos
  become: true
  roles:
    - deploy-basic

