#*  This playbook wrapps the copy module. It passes the most basic
#* configs for each host from a list to 'dest'. Use '-a' to pass
#* further parameters to ansible (as '-e'). See ansible fetch for
#* details. 
#*  You might want to do set a temporary workdir `nodeify.sh -w dir`
#* or do a `nodeify.sh merge-all` first and then merge manually back
#* to the storage dir. 
#*  No arguments are needed.

- hosts: os.debian
  become: true
  roles:
    - deploy-basic

