#*  This playbook simply wrapps the file module. Depending on the
#* 'state' argument provided, it will pass the request to the
#* corresponding role. As this simplifies the module usage, some
#* features will possibly be missing. Note: see the other 'file'
#* playbooks too for shortcuts: ch_file, ..
#*  The following arguments are mandatory:
#*   - 'file' (aliases: 'path', 'dest', 'name')
#*   - 'state' (see file_module)
#* For optional arguments, please read the corresponding role and
#* consult http://docs.ansible.com/ansible/latest/file_module.html
#*

- hosts: all
  vars:
    file: '{{ path | d(dest) | d(name) }}'
    owner: '{{ user }}'
  roles:
    - { role: ch-own-mod, when: state == 'file' }
    - { role: file-touch, when: state == 'touch' }
