#*  This playbook simply wrapps the file module. It simulates the
#* famous CLI tool 'touch'. New files/dirs are created, existing
#* ones get new access/modification times.
#*  As this simplifies both the tools and the file module usage,
#* some features will possibly be missing.
#*  The following arguments are mandatory:
#*   - 'file' (aliases: 'path', 'dest', 'name')
#*   - 'state' (see file_module)
#*  The following arguments are optional:
#*

- hosts: all
  vars:
    file: '{{ path | d(dest) | d(name) }}'
  roles:
    - file-touch
