#*  This playbook simply wrapps the file module. It simulates the
#* famous CLI tool 'ln -s'. Create symlinks to the source specified.
#*  As this simplifies both the tool and the file module usage,
#* some features will possibly be missing.
#*  The following arguments are mandatory:
#*   - 'path' (aliases: 'dest', 'name', 'file')
#*   - 'src'
#*  The following arguments are optional:
#*   - [ 'owner' ]
#*   - [ 'group' ]
#*   - [ 'mode' ]
#*

- hosts: all
  vars:
    state: 'link'
    path: '{{ file | d(dest) | d(name) }}'
    owner: '{{ user }}'
  roles:
    - file-link
    - file-change
