#*  This playbook simply wrapps the file module. It simulates the
#* famous CLI tools 'mkdir'/'chmod'/'chown'/'chgrp'. New dirs are
#* created, user/group and permissions are set.
#*  As this simplifies both the tools and the file module usage,
#* some features will possibly be missing.
#*  The following arguments are mandatory:
#*   - 'dir' (aliases: 'path', 'dest', 'name', 'file')
#*  The following arguments are optional:
#*   - [ 'owner' ]
#*   - [ 'group' ]
#*   - [ 'mode' ]
#*

- hosts: all
  vars:
    file: '{{ path | d(dest) | d(name) | d(dir) }}'
    owner: '{{ user }}'
  roles:
    - file-dir
