#*  This playbook simply wrapps the file module. It simulates the
#* famous CLI tools 'chmod'/'chown'/'chgrp', and will set the
#* user/group and permissions requested on the file or directory.
#*  As this simplifies both the tools and the file module usage,
#* some features will possibly be missing.
#*  The following arguments are mandatory:
#*   - 'file' (aliases: 'path', 'dest', 'name')
#*   - 'state' (see file_module)
#*  The following arguments are optional:
#*   - [ 'owner' ]
#*   - [ 'group' ]
#*   - [ 'mode' ]
#*

- hosts: all
  vars:
    state: 'file'
    file: '{{ path | d(dest) | d(name) }}'
    owner: '{{ user }}'
  roles:
    - file-change
