#*  This playbook simply wrapps the fetch module. Per default it gets
#* a certain file from the server and puts it in the workdir.
#*  The following arguments are mandatory:
#*   - ( 'file' ) or ( 'src' and 'dest' )

- hosts: all

  roles:
    - fetch
