#*  This playbook downloads, unpacks, and installes our customized liferay
#* packages (without enabling it yet though - see install-liferay-enabled/
#* install-liferay-disabled too).
#*  Note: this playbook should be used either from the main install playbook
#* (which resolves its dependencies) or as a shorthand for an already set up
#* system, where the dependencies are already provided.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: app.liferay
  become: True
  roles:
    - { role: zwischenloesung.yapkg, yapkg_group_name: 'preview generation', yapkg_names: [ 'imagemagick', 'ghostscript' ] }

- hosts: app.liferay.v7
  become: True

  roles:
    - install-liferay-unbundled
#    - install-liferay-plugins

- hosts: app.liferay.v6
  become: True

  roles:
    - install-liferay
    - install-liferay-plugins

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

