#*  This playbook wrappes the apt (and others maybe in the future..) module
#* to install software for terminal multiplexing and offline sessions..
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: host.KVM, host.Virtual

  roles:
    - install-screen
    - install-tmux

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

