#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install software for virtualization via KVM.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- include: install-basic.yml

- hosts: host.KVM

  roles:
    - install-netcat
    - install-libvirt

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

