#*  This playbook installs the environement for php based projects.
#*  Note: this playbook should be used either from the main install playbook
#* (which resolves its dependencies) or as a shorthand for an already set up
#* system, where the dependencies are already provided.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: app.php.5,!app.php.fpm
  become: True
  roles:
    - { role: inofix.yapkg, yapkg__task_group_name: 'php5', yapkg__list: [ 'php_5', 'php' ] }

- hosts: app.php.7.0,!app.php.fpm
  become: True
  roles:
    - { role: inofix.yapkg, yapkg__task_group_name: 'php7.0', yapkg__list: [ 'php_7_0', 'php' ] }

- hosts: app.php,!app.php.7.0,!app.php.5,!app.php.fpm
  become: True
  roles:
    - { role: inofix.yapkg, yapkg__task_group_name: 'php7.0', yapkg__list: [ 'php' ] }

- hosts: app.php.fpm
  become: True
  vars:
    # set the pkg list here for now..
    app__php__yapkg__list: '{{ os__pkg_name | select("equalto", app__php__pkg_key) | list }}'
  roles:
    - inofix.php-fpm

- hosts: app.php.fpm,&app.shariff.php
  become: True
  roles:
    - inofix.shariff-php

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

