#*  This playbook downloads, unpacks, and installes our customized liferay
#* packages. It will also install dependencies such as a container and a
#* database and connect them together.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- include: install-basic.yml
- include: install-tomcat.yml

- hosts: app.liferay.v7
  become: True

  roles:
    - install-liferay-unbundled

- hosts: app.liferay.v6
  become: True

  roles:
    - install-liferay

- include: enable-liferay.yml

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

