---
#*  This playbook wrapps the debops.postgresql (for now) Ansible role
#  to install and manage the PostgreSQL DB server.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  Check the following link for a list of possible configuration variables:
#* https://docs.debops.org/en/latest/ansible/roles/ansible-postgresql/docs/defaults.html
#*  No arguments are mandatory.

- name: Setup PostgreSQL Server
  hosts: app.postgresql.server
  become: True
  roles:
    - debops.postgresql_server

- name: Setup PostgreSQL Client
  hosts: app.postgresql.client,!app.postgresql.server
  become: True
  roles:
    - debops.postgresql
