#*  This playbook wrapps the apt (and others maybe in the future..) module
#* to install software for virtualization via KVM.
#*  Note: this playbook should be used either from the main install playbook
#* (which resolves its dependencies) or as a shorthand for an already set up
#* system, where the dependencies are already provided.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

- hosts: host.KVM
  become: True
  roles:
    - inofix.yapkg
  vars:
    - yapkg__task_group_name: 'netcat'
    - yapkg__names:
      - 'netcat-openbsd'

- hosts: host.KVM, &os.debian
  become: True
  roles:
    - { role: inofix.yapkg, when: 'ansible_virtualization_role == "host"' }
  vars:
    - yapkg__task_group_name: 'libvirt part I'
    - yapkg__names:
      - 'virtinst'
      - 'virt-top'

- hosts: host.KVM, &os.debian_jessie
  become: True
  roles:
    - { role: inofix.yapkg, when: 'ansible_virtualization_role == "host"' }
  vars:
    - yapkg__task_group_name: 'libvirt part II'
    - yapkg__names:
      - 'libvirt-bin'

- hosts: os.debian_stretch, os.debian_buster, &host.KVM, &host.Metal
  become: True
  roles:
    - { role: inofix.yapkg, when: 'ansible_virtualization_role == "host"' }
  vars:
    - yapkg__task_group_name: 'libvirt part II'
    - yapkg__names:
      - 'libvirt-daemon-system'

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

