#*  This playbook installs acme-tiny either from the distro or directly
#* from upstream github if there is no package available.
#*  Note: this playbook should be used either from the main install playbook
#* (which resolves its dependencies) or as a shorthand for an already set up
#* system, where the dependencies are already provided.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  No arguments are mandatory.

# Do only on hosts with the acme-tiny application actually installed
- hosts: app.acme.tiny,&app.acme.sign
  become: True
  roles:
    - inofix.acme-tiny-install
    - inofix.acme-tiny-cron

# not enabling this yet, as it only tracks 'today'
# it is only useful for human communication and needs
# to be combined with something smarter as
# dpkg --get-selections
#- hosts: all

#  roles:
#    - track-packages

