---
#*  This playbook wrapps the debops.apache Ansible role to install and
#* manage the Apache httpd Web server.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  Check the following link for a list of possible configuration variables:
#* https://docs.debops.org/en/latest/ansible/roles/ansible-apache/docs/defaults.html
#*  No arguments are mandatory.

- name: Setup Apache httpd Web server
  hosts: app.apache
  become: True

  vars:
    # define custom vhosts
    apache__vhosts: '{{ app__apache__vhosts }}'
    apache__modules: '{{ app__apache__modules }}'

    # build up the correct ssl path to allow crt
    # and key configurations relative to /etc/ssl
    apache__pki_realm_path: '/etc'
    apache__pki_realm: 'ssl'
    apache__pki_ca_filename: '{{ app__apache__pki_ca_filename }}'

    apache__default_vhost:
      name: '{{ ansible_fqdn }}'
      root: '/var/www/html'
      # don't enforce https by default
      redirect_to_https: False

  roles:
    - debops.apache/env
    - debops.apache
