#*  This playbook wrapps the fetch module. It passes the configs related
#* to libreoffice for each host as a list to 'src'. Use '-a' to pass
#* further parameters to ansible (as '-e'). See ansible fetch for
#* details. 
#*  You might want to do a `maestro.sh merge` first and then
#* merge manually back to the storage dir in order to see all the
#* diffs right away.
#*  No arguments are needed.

- hosts: app.libreoffice

  roles:
    - persist-libreoffice

