#*  This playbook simply wrappes the copy module. Use '-a' to pass
#* parameters to ansible (as '-e'). See ansible copy for details.
#*  The following arguments are mandatory:
#*   - 'dest'

- hosts: all

  roles:
    - copy
