#*  This playbook makes sure the cronjob for acme-tiny is ready.
#*  Note: this playbook has a dependency to setup-letsencrypt and is mainly
#* for fixing issues, so if you are not really sure what you are doing, use
#* setup-letsencrypt instead.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  The following arguments are mandatory:
#*   - 'app__acme__tiny__domain'

# Do only on hosts with the acme-tiny application actually installed
- hosts: app.acme.tiny
  become: True
  roles:
    - { role: zwischenloesung.acme-tiny-cron }

