#*  This playbook installs and prepares everything for acme-tiny for a certain
#* domain, which is declared by 'app__acme__domain'.
#*  Note: this playbook should be used either from the main install playbook
#* (which resolves its dependencies) or as a shorthand for an already set up
#* system, where the dependencies are already provided.
#*  Use '-a' to pass parameters to ansible (as '-e'). See ansible fetch for
#* details.
#*  The following arguments are mandatory:
#*   - 'app__acme__domain'

# Do on all hosts related to acme which do not sign themselves
- hosts: app.acme,!app.acme.sign
  become: True
  roles:
    - { role: inofix.acme-request }
    - { role: inofix.acme-proxy }

# Do only on hosts with the acme-tiny application actually installed
- hosts: app.acme.tiny,&app.acme.sign
  become: True
  roles:
    - { role: inofix.acme-request }
    - { role: inofix.acme-tiny-sign }
    - { role: inofix.acme-tiny-cron }

# Restart the service
- hosts: app.acme,&app.apache
  become: True
  roles:
    - { role: inofix.acme-service, app__acme__service_name: 'apache' }

# Restart the service
- hosts: app.acme,&app.dovecot
  become: True
  roles:
    - { role: inofix.acme-service, app__acme__service_name: 'dovecot' }

# Restart the service
- hosts: app.acme,&app.nginx
  become: True
  roles:
    - { role: inofix.acme-service, app__acme__service_name: 'nginx' }

# Restart the service
- hosts: app.acme,&app.postfix
  become: True
  roles:
    - { role: inofix.acme-service, app__acme__service_name: 'postfix' }

# Restart the service
- hosts: app.acme,&app.prosody
  become: True
  roles:
    - { role: inofix.acme-service, app__acme__service_name: 'prosody' }


