---
- name: download and deploy liferay plugins
  environment:
    http_proxy: "{{ http_proxy }}"
  get_url:
    checksum: "{{ item.checksum }}"
    dest: "{{ remotedirs.service }}/{{ item.file }}"
    url: "{{ item.url }}"
    owner: "{{ app__liferay__user }}"
    group: "{{ app__liferay__group }}"
  with_items: "{{ app__liferay__plugin }}"

