- name: install apt-show-versions
  apt:
    name: apt-show-versions
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: install cron-apt
  apt:
    name: cron-apt
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
