
- name: gather the passwords file from the host itself
  shell: 'cat {{ account_store }}'
  register: accountsfile

- name: parse the file for passwords
  set_fact: 'accountinfos={{ accountsfile.stdout | from_yaml }}'

- name: set the correct password to the file
  lineinfile:
    dest: '{{ account_dest }}'
    regexp: "^{{ account_pass_key }}=.*"
    line: "{{ account_pass_key }}={{ accountinfos[account_section][value_to_use] }}"
  when: account_dest_file_type == "key=val"

- name: set the correct password to the file
  lineinfile:
    dest: '{{ account_dest }}'
    regexp: '^( *).{{ account_pass_key }}.: .*(,?)$'
# TODO: if I try to use (.) -> \2 instead of '"', then somehow the third \2 (which should be a quote) is interpreted as char code if it is followed directly with some number..
#    line: '\\1\\2{{ account_pass_key }}\\2: \\2{{ accountinfos[account_section][value_to_use] }}\\2\\3'
    line: '\1"{{ account_pass_key }}": "{{ accountinfos[account_section][value_to_use] }}"\2'
    backrefs: yes
  when: account_dest_file_type == "json"

