src_files: '{{ service__monitoring__icinga__root_root_644_files + service__monitoring__icinga__root_nagios_640_files + service__monitoring__icinga__nagios_nagios_600_files }}'
dest: '{{ workdir }}'
account_dest: '{{ workdir }}/{{ fqdn }}/etc/icinga/ido2db.cfg'
account_store: '{{ account_store }}'
account_section: 'icinga_db'
account_pass_key: 'db_pass'
account_password_placeholder: '{{ account_password_placeholder }}'
fail_on_missing: no
flat:
validate_checksum: yes

