---
# mutually exclusive credentail patterns:
format:
  properties:
    backrefs: false
    line: "{{ account_key }}={{ account_password_placeholder }}"
    regexp: "^{{ account_key }}=.*"
  ini:
    backrefs: false
    line: "{{ account_key }} = {{ account_password_placeholder }}"
    regexp: "^{{ account_key }} = .*"
  json:
    backrefs: true
# TODO: if I try to use (.), to match the 4 quotes (which would then become
# \2), then somehow the third \2 is interpreted as char code instead of the
# regexp placeholder, if it is followed directly by some digit (e.g. \256)
    line: '\1"{{ account_key }}": "{{ account_password_placeholder }}"\2'
    regexp: '^( *).{{ account_key }}.: .*(,?)$'
