---
dependencies:
  - deploy-account-store
  - { role: add-credentials-to-store, target_file: '{{ app__liferay__config }}', credentials_key: '{{ liferay_db_credentails_key }}', credentials_name: '{{ liferay_db_credentails_name }}' }

