---
dependencies:
  - deploy-account-store
  - { role: add-credentials-to-store, target_file: '{{ app__liferay__config }}', password_tmp_file: '{{ default__password_tmp_file }}', password_length: '{{ default__password_length }}', password__chars: '{{ default__password_chars }}' }

