---
dependencies:
  - deploy-account-store
  - { role: add-credentials-to-store, target_file: '{{ app__liferay__config }}', credentials_key: '{{ default__liferay_db_credentials_key }}', credentials_name: '{{ default__liferay_db_credentails_name }}' }

