---
- name: Create a dedicated group
  group:
    name: '{{ group }}'
    system: True

- name: Create a dedicated user
  user:
    name: '{{ user }}'
    group: '{{ group }}'
    system: True
    home: '{{ users_home }}'
    createhome: True

- name: Install the start-stop-daemon-script
  template:
    src: 'startstop_libreoffice.yml'
    dest: '/etc/init.d/libreoffice'
    mode: '0755'
    owner: 'root'
    group: 'root'

