---
- name: Create a dedicated group
  group:
    name: 'libreoffice'
    system: True

- name: Create a dedicated user
  user:
    name: 'libreoffice'
    group: 'libreoffice'
    system: True
    home: '/var/lib/libreoffice-home'
    createhome: True

- name: Install the start-stop-daemon-script
  template:
    src: 'startstop_libreoffice.yml'
    dest: '/etc/init.d/libreoffice'
    mode: '0755'
    owner: 'root'
    group: 'root'
