
# add it in a controlled way..

- name: make sure backports is present
  lineinfile:
    dest: /etc/apt/sources.list.d/backports.list
    state: present
    create: yes
    line: "deb http://ftp.debian.org/debian wheezy-backports main"
  when: ansible_os_family == "Debian" and ansible_distribution_release == "wheezy"

- name: make sure backports is present
  lineinfile:
    dest: /etc/apt/sources.list.d/backports.list
    state: present
    create: yes
    line: "deb http://ftp.debian.org/debian jessie-backports main"
  when: ansible_os_family == "Debian" and ansible_distribution_release == "jessie"

- name: update the repository index
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

