---

- name: make sure the rc default config exists
  file:
    state: 'touch'
    dest: '/etc/default/rcS'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: install a very simplistic init script
  template:
    src: 'thewall.j2'
    dest: '/etc/init.d/thewall'
    owner: 'root'
    group: 'root'
    mode: '0755'

# for now the rules are installed from the repo
