---
dependencies:
  - deploy-account-store
  - { role: add-credentials-to-store, target_file: '{{ nextcloud__config }}', credentials_key: '{{ nextcloud__db_credentials_key }}', credentials_name: '{{ nextcloud__db_credentials_name }}', credentials_user: '{{ nextcloud__db_user }}', password_chars: "ascii,digits,.-_~+=" }

