src: '{{ workdir }}/{{ fqdn }}/{{ app__liferay__config }}'
dest: '{{ app__liferay__config }}'
owner: '{{ app__tomcat__user }}'
group: '{{ app__tomcat__group }}'
mode: 0640
backup: no
force: yes
account_dest: '{{ dest }}'
account_dest_file_type: "key=val"
#account_store: from project/any.yml
account_section: 'liferay_db'
account_pass_key: 'jdbc.default.password'

