
# in jessie, the backports repo is needed..
- include: roles/add-backports/tasks/main.yml
  vars:
    apt_update_index: false
  when: ansible_os_family == "Debian" and ansible_distribution_release == "jessie"

- name: install check-mk-agent
  apt:
    name: check-mk-agent
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  vars:
    just_installed_cmka: true

- name: install the icinga/nagios group
  group:
    name: nagios
    gid: 133
    state: 'present'
    system: 'yes'
  when: just_installed_cmka == true

- name: install the icinga/nagios user
  user:
    name: nagios
    uid: 133
    group: nagios
    home: /var/lib/nagios
    shell: /bin/sh
  when: just_installed_cmka == true

- name: create the ssh config directory for the user nagios
  file:
    state: directory
    dest: /var/lib/nagios/.ssh
    mode: 0700
    owner: nagios
    group: nagios
  when: just_installed_cmka == true

- name: create ssh config authorized_keys for nagios
  template:
    src: roles/install-cmk-a/files/authorized_keys
    dest: /var/lib/nagios/.ssh/authorized_keys
    mode: 0600
    owner: nagios
    group: nagios
  when: just_installed_cmka == true

- name: create the sudo config
  copy:
    src: roles/install-cmk-a/files/sudoers_nagios
    dest: /etc/sudoers.d/nagios
    mode: 0440
    owner: root
    group: root
  when: just_installed_cmka == true

- name: make sure monitoring host may log in
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    insertafter: "AllowUsers.*"
    line: "AllowUsers nagios@{{ role__monitored__by_ip }}"
  when: just_installed_cmka == true


