- name: install ntpdate
  apt:
    name: ntpdate
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: install ntp
  apt:
    name: ntp
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
