---
- name: Gather the passwords file from the host itself.
  shell: 'cat {{ a_store }}'
  register: accountsfile

- name: Parse the file for passwords.
  set_fact: 'accountinfos={{ accountsfile.stdout | from_yaml }}'

- name: add an entry containing credentials for a certain service
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK: {{ c_name }}'
    backup: true
    dest: '{{ a_store }}'
    block: |
      {{ c_name }}:
        file: "{{ t_file }}"
        user: "{{ c_user }}"
        key: "{{ c_key }}"
        value: "{{ password }}"
  when: accountinfos[c_name] is not defined

- name: clean up the temporary local password file
  become: false
  connection: local
  file:
    state: absent
    path: '{{ ptf }}'
