
- name: test if liferay was installed
  stat:
    path: '{{ remotedirs.service }}/{{ app__liferay__name }}/portal-ext.properties'
  register: liferay_config

- name: fail if the installation is missing
  fail:
    msg: "Liferay was not installed correctly on {{ remotedirs.service }}/{{ app__liferay__name }}"
  when: liferay_config.stat.isreg is not defined or not liferay_config.stat.isreg

- name: test if the setup was already done
  stat:
    path: '{{ app__liferay__worklink }}'
  register: liferay_link

- name: stop tomcat
  service:
    name: '{{ app__tomcat__name }}'
    state: stopped
  when: liferay_link.stat.islnk is not defined or liferay_link.stat.lnk_source != '{{ remotedirs.service }}/{{ app__liferay__name }}'

- name: check whether the old webapps was already disabled once
  stat:
    path: '/var/lib/{{ app__tomcat__name }}/webapps_ansible_disabled'
  register: tomcat_webapps_stat

- name: link the current liferay version to the default path
  file:
    state: link
    src: '{{ remotedirs.service }}/{{ app__liferay__name }}'
    dest: '{{ app__liferay__worklink }}'
    force: True
  when: liferay_link.stat.islnk is not defined or liferay_link.stat.lnk_source != '{{ remotedirs.service }}/{{ app__liferay__name }}'

- name: move the old tomcat webapps out of the way
  when: not tomcat_webapps_stat.stat.exists
  command: mv '/var/lib/{{ app__tomcat__name }}/webapps' '/var/lib/{{ app__tomcat__name }}/webapps_ansible_disabled'

- name: link liferay webapps into the tomcat directory
  when: not tomcat_webapps_stat.stat.exists
  file:
    state: link
    dest: '/var/lib/{{ app__tomcat__name }}/webapps'
    src: '{{ app__liferay__webapps }}'

- name: create bin/ and lib/ directories for the new tomcat
  file:
    dest: "{{ remotedirs.service }}/{{ app__liferay__name }}/{{ app__liferay__containername }}/{{ item }}"
    state: directory
    owner: "{{ app__liferay__user }}"
    group: "{{ app__liferay__group }}"
    recurse: yes
  with_items:
    - "bin"
    - "lib"

- name: register the content of the tomcat installations bin/ directory
  command: 'ls {{ app__tomcat__installation }}/bin/'
  register: tomcat_bins

- name: register the content of the tomcat installations bin/ directory
  command: 'ls {{ app__tomcat__installation }}/lib/'
  register: tomcat_libs

- name: link the contents of bin/ from the tomcat installation to the new tomcat directory
  file:
    state: link
    src: "{{ app__tomcat__installation }}/bin/{{ item }}"
    dest: "{{ app__liferay__container_dir }}/bin/{{ item }}"
    owner: "{{ app__liferay__user }}"
    group: "{{ app__liferay__group }}"
  with_items: "{{ tomcat_bins.stdout_lines }}"

- name: link the contents of lib/ from the tomcat installation to the new tomcat directory
  file:
    state: link
    src: "{{ app__tomcat__installation }}/lib/{{ item }}"
    dest: "{{ app__liferay__container_dir }}/lib/{{ item }}"
    owner: "{{ app__liferay__user }}"
    group: "{{ app__liferay__group }}"
  with_items: "{{ tomcat_libs.stdout_lines }}"

- name: link liferay portal properties to system lib
  file:
    state: link
    dest: '/var/lib/portal-ext.properties'
    src: '{{ app__liferay__home }}/portal-ext.properties'

- name: edit the main tomcat server.xml
  replace:
    dest: '{{ app__tomcat__config }}'
    regexp: 'name="localhost"\s*appBase="webapps"'
    replace: 'name="localhost"  appBase="{{ app__liferay__webapps }}/"'

- name: edit the catalina properties, add liferay dependency .jar-libraries to common.loader
  replace:
    dest: '{{ app__tomcat__properties }}'
    regexp: '^common\.loader=.*'
    replace: 'common.loader=${catalina.base}/lib,${catalina.base}/lib/*.jar,${catalina.home}/lib,${catalina.home}/lib/*.jar,{{ app__liferay__worklink }}/{{ app__liferay__containername }}/lib/ext/*.jar'

- name: edit the catalina properties, unset server.loader
  replace:
    dest: '{{ app__tomcat__properties }}'
    regexp: '^server\.loader=.*'
    replace: 'server.loader='

- name: edit the catalina properties, unset shared.loader
  replace:
    dest: '{{ app__tomcat__properties }}'
    regexp: '^shared\.loader=.*'
    replace: 'shared.loader='

- name: create the configuration descriptor ROOT.xml
  template:
    dest: '{{ app__tomcat__workroot }}'
    src: 'ROOT.xml'
    group: "{{ app__liferay__group }}"
    owner: "{{ app__liferay__user }}"
    mode: "0644"
#  blockinfile:
#    create: True
#    dest: '{{ app__tomcat__workroot }}'
#    marker: '<!-- {mark} ANSIBLE MANAGED BLOCK -->'
#    block: |
#      <Context path="" crossContext="true">
#      </Context>

- name: edit tomcat startup file for (probably) more RAM etc.
  lineinfile:
    dest: '{{ app__tomcat__startup }}'
    insertafter: '^JAVA_OPTS="-'
    line: 'JAVA_OPTS="${JAVA_OPTS} -Djava.net.preferIPv4Stack=true -Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false -Xms{{ app__liferay__xms }} -Xmx{{ app__liferay__xmx }} -XX:MaxPermSize={{ app__liferay__xxmaxpermsize }} -Duser.timezone=GMT -Dfile.encoding=UTF8"'

- name: edit tomcat startup for development hosts
  lineinfile:
    dest: '{{ app__tomcat__startup }}'
    insertafter: '^JAVA_OPTS="-'
    line: 'JAVA_OPTS="${JAVA_OPTS} -Dexternal-properties=portal-developer.properties"'
  when: role == 'development'

- name: edit tomcat startup for development hosts
  lineinfile:
    dest: '{{ app__tomcat__startup }}'
    state: absent
    line: 'JAVA_OPTS="${JAVA_OPTS} -Dexternal-properties=portal-developer.properties"'
  when: role != 'development'

- name: use the non-default java version 8 for jessie in tomcat startup config
  lineinfile:
    dest: '{{ app__tomcat__startup }}'
    insertafter: '^#JAVA_HOME='
    line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64'
  when:
    - os__distro == "debian"
    - os__codename == "jessie"
    - app__java__version == "8"

- name: start tomcat
  service:
    name: '{{ app__tomcat__name }}'
    state: started
  when: liferay_link.stat.islnk is not defined or liferay_link.stat.lnk_source != '{{ remotedirs.service }}/{{ app__liferay__name }}'

- name: prepare an upgrade config, just in case
  blockinfile:
    create: yes
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg }}//tools/portal-tools-db-upgrade-client/app-server.properties"
    owner: "{{ app__liferay__user }}"
    group: "{{ app__liferay__group }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Container"
    block: |
      dir={{ remotedirs.service }}/{{ app__liferay__pkg }}/container
      global.lib.dir=lib
      portal.dir=webapps/ROOT
      server.detector.server.id=tomcat
      extra.lib.dirs=bin
  when:
    - app__liferay__version_major >= '7.0'

