---
- name: 'Install a basic config file'
  template:
    src: 'vimrc.j2'
    dest: '/etc/vim/vimrc'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Overwrite the default if the workdir knows better'
  copy:
    src: '{{ workdir }}/{{ fqdn }}/{{ app__vim__config }}'
    dest: '{{ app__vim__config }}'
    owner: 'root'
    group: 'root'
    mode: 0644
    backup: no
  ignore_errors: yes

- name: make vim the default editor
  shell: update-alternatives --set editor /usr/bin/vim.basic

