- name: install vim
  apt:
    name: vim
    update_cache: yes
  when: ansible_os_family == "Debian"
  vars:
    just_installed_vim: true

- name: install vim config
  copy:
    src: '{{ workdir }}/{{ fqdn }}/{{ app_vim_config }}'
    dest: '{{ app_vim_config }}'
    owner: 'root'
    group: 'root'
    mode: 0644
    backup: no
  when: just_installed_vim == true

- name: make vim the default editor
  shell: update-alternatives --set editor /usr/bin/vim.basic
  when:  just_installed_vim == true

