- name: install vim config
  copy:
    src: '{{ workdir }}/{{ fqdn }}/{{ app_vim_config }}'
    dest: '{{ app_vim_config }}'
    owner: 'root'
    group: 'root'
    mode: 0644
    backup: no
  ignore_errors: yes

- name: make vim the default editor
  shell: update-alternatives --set editor /usr/bin/vim.basic

