- name: install vim
  apt:
    name: vim
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: install vim config
  copy:
    src: '{{ workdir }}/{{ fqdn }}/{{ app_vim_config }}'
    dest: '{{ app_vim_config }}'
    owner: 'root'
    group: 'root'
    mode: 0644
    backup: no

- name: make vim the default editor
  shell: update-alternatives --set editor /usr/bin/vim.basic

