
- name: test if liferay was installed
  stat:
    path: '{{ remotedirs.service }}/{{ app__liferay__name }}/portal-ext.properties'
  register: liferay_config

- name: fail if the installation is missing
  fail:
    msg: "Liferay was not installed correctly on {{ remotedirs.service }}/{{ app__liferay__name }}"
  when: liferay_config.stat.isreg is not defined or not liferay_config.stat.isreg

- name: Gather the passwords file from the host itself.
  shell: 'cat {{ account_store }}'
  register: accountsfile

- name: Parse the file for passwords.
  set_fact: 'accountinfos={{ accountsfile.stdout | from_yaml }}'

- name: create a db user for the liferay db
  postgresql_user:
    name: '{{ app__liferay__db_user }}'
    password: '{{ accountinfos[liferay_db_credentails_name]["value"] }}'

- name: create a db for liferay
  postgresql_db:
    name: '{{ app__liferay__db_name }}'
    owner: '{{ app__liferay__db_user }}'
    encoding: UTF-8
    template: template0

