src_files: '{{ app__backupninja__d_task | map(attribute="file") | list() }}'
dest: '{{ workdir }}'
#mode: 0640
account_file_list: '{{ app__backupninja__d_task | rejectattr("credentials", "undefined") | selectattr("credentials") | selectattr("dup") | list() }}'
account_file_type: "ini"
#account_store: from project/any.yml
account_section: 'backupninja_dup'
account_key: 'password'
#account_password_placeholder: from project/any.yml
fail_on_missing: no
flat:
validate_checksum: yes
mode: 0644

