- name: check for installation
  stat:
    path: "{{ remotedirs.service }}/{{ app__liferay__pkg }}"
  register: lr_stat

- name: download liferay
  environment:
    http_proxy: "{{ http_proxy }}"
  get_url:
    checksum: "{{ app__liferay__checksum }}"
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg_archive }}"
    url: "{{ app__liferay__pkg_url }}"
  when: lr_stat.stat.isdir is not defined

- name: unpack liferay
  unarchive:
    remote_src: yes
    creates: "{{ remotedirs.service }}/{{ app__liferay__pkg }}/portal-ext.properties"
    dest: "{{ remotedirs.service }}/"
    src: "{{ remotedirs.service }}/{{ app__liferay__pkg_archive }}"

- name: change the ownership
  file:
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg }}"
    state: directory
    owner: "{{ app__tomcat__user }}"
    group: "{{ app__tomcat__group }}"
    recurse: yes

- name: change liferay home in properties
  replace:
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg }}/portal-ext.properties"
    mode: 0600
    owner: "{{ app__tomcat__user }}"
    group: "{{ app__tomcat__group }}"
    regexp: "liferay.home=%LIFERAY_HOME%"
    replace: "liferay.home={{ app__liferay__home }}"

- name: disable the setup whizzard
  blockinfile:
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg }}/portal-ext.properties"
    insertafter: "liferay.home={{ app__liferay__home }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: WHIZZARD"
    block: |
      setup.wizard.add.sample.data=false
      setup.wizard.enabled=false
  when:
    - app__liferay__setup_whizzard == false

- name: add a note about the docu for properties
  lineinfile:
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg }}/portal-ext.properties"
    line: "# See https://docs.liferay.com/portal/{{ app__liferay__version_major }}/propertiesdoc/portal.properties.html #"
    insertbefore: BOF

#- name: install liferay

