- name: check for installation
  command: ls "{{ remotedirs.service }}/{{ app__liferay__pkg }}"
  register: contents

- name: download liferay
  environment:
    http_proxy: "{{ http_proxy }}"
  get_url:
    checksum: "{{ app__liferay__checksum }}"
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg_archive }}"
    url: "{{ app__liferay__pkg_url }}"
  when: contents.stdout == ""

- name: unpack liferay
  unarchive:
    remote_src: yes
    copy: no
    creates: "{{ remotedirs.service }}/{{ app__liferay__pkg }}/portal-ext.properties"
    dest: "{{ remotedirs.service }}/"
    src: "{{ remotedirs.service }}/{{ app__liferay__pkg_archive }}"

- name: change the ownership
  file:
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg }}"
    state: directory
    owner: "{{ app__tomcat__user }}"
    group: "{{ app__tomcat__group }}"
    recurse: yes

- name: change liferay home in properties
  replace:
    dest: "{{ remotedirs.service }}/{{ app__liferay__pkg }}/portal-ext.properties"
    mode: 0600
    owner: "{{ app__tomcat__user }}"
    group: "{{ app__tomcat__group }}"
    regexp: "liferay.home=%LIFERAY_HOME%"
    replace: "liferay.home={{ app__liferay__home }}"

#- name: install liferay

