- name: get files from the remote host
  fetch:
    src: '{{ item }}'
    dest: '{{ dest }}'
    fail_on_missing: '{{ fail_on_missing }}'
    flat: '{{ flat }}'
    mode: '{{ mode }}'
    validate_checksum: '{{ validate_checksum }}'
  with_items: "{{ src_files }}"
